name: Run Cypress tests google form submission

on:
  push:
    branches:
      - main  # Run on push to the main branch

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test
      - name: Add executable permissions
        run: chmod +x ./node_modules/.bin/cypress

      - name: Run Cypress tests
        run: ./node_modules/.bin/cypress run
        