name: google form browser test e2e
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: "cypress/integration/googleFormSubmission_Test.cy.js"

          browser : chrome